// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrs4mcdPSmOhs9aws2bt59oizsx8Zb6bQ',
    appId: '1:273967639298:web:539ce9b0c5f9bdbcbef01b',
    messagingSenderId: '273967639298',
    projectId: 'calorie-tracker-101e2',
    authDomain: 'calorie-tracker-101e2.firebaseapp.com',
    storageBucket: 'calorie-tracker-101e2.appspot.com',
    measurementId: 'G-G6B8N2SSJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPSE-HRBmeu963Wq1IJ8seJErD3UDvKU',
    appId: '1:273967639298:android:e6d3809e2e90b1d2bef01b',
    messagingSenderId: '273967639298',
    projectId: 'calorie-tracker-101e2',
    storageBucket: 'calorie-tracker-101e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZK4DN8YyoY8gagYWzrjtJox6nYkhIcY',
    appId: '1:273967639298:ios:a82d506d95ab3687bef01b',
    messagingSenderId: '273967639298',
    projectId: 'calorie-tracker-101e2',
    storageBucket: 'calorie-tracker-101e2.appspot.com',
    androidClientId:
        '273967639298-qjq64cs8knelfhbmao360u9t89blchb4.apps.googleusercontent.com',
    iosClientId:
        '273967639298-k8uunmfl4ouj7r0p98cdde9klbca9rmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTrackerr',
  );
}
